title: Talking about problems that were fixed by talking to a duck.
author: James VanTrieste
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  This site is to talk about coding problems that were solved by talking to the rubber duck on your desk.

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
